# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vilay/ui/main.ui'
#
# Created: Wed Apr 17 19:31:59 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_vilaydetect(object):
    def setupUi(self, vilaydetect):
        vilaydetect.setObjectName(_fromUtf8("vilaydetect"))
        vilaydetect.resize(788, 552)
        self.verticalLayout_4 = QtGui.QVBoxLayout(vilaydetect)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setContentsMargins(4, 2, 4, 4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mainToolBarFrame = QtGui.QFrame(vilaydetect)
        self.mainToolBarFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.mainToolBarFrame.setObjectName(_fromUtf8("mainToolBarFrame"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.mainToolBarFrame)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.menuNew = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuNew.setMinimumSize(QtCore.QSize(38, 38))
        self.menuNew.setMaximumSize(QtCore.QSize(38, 38))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.menuNew.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/New file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuNew.setIcon(icon)
        self.menuNew.setIconSize(QtCore.QSize(24, 24))
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.horizontalLayout_6.addWidget(self.menuNew)
        self.menuLoad = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuLoad.setMinimumSize(QtCore.QSize(38, 38))
        self.menuLoad.setMaximumSize(QtCore.QSize(38, 38))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuLoad.setIcon(icon1)
        self.menuLoad.setIconSize(QtCore.QSize(24, 24))
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.horizontalLayout_6.addWidget(self.menuLoad)
        self.menuSave = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuSave.setMinimumSize(QtCore.QSize(38, 38))
        self.menuSave.setMaximumSize(QtCore.QSize(38, 38))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuSave.setIcon(icon2)
        self.menuSave.setIconSize(QtCore.QSize(24, 24))
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.horizontalLayout_6.addWidget(self.menuSave)
        self.line_2 = QtGui.QFrame(self.mainToolBarFrame)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_6.addWidget(self.line_2)
        self.menuImport = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuImport.setMinimumSize(QtCore.QSize(38, 38))
        self.menuImport.setMaximumSize(QtCore.QSize(38, 38))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuImport.setIcon(icon3)
        self.menuImport.setIconSize(QtCore.QSize(24, 24))
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        self.horizontalLayout_6.addWidget(self.menuImport)
        self.menuExport = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuExport.setMinimumSize(QtCore.QSize(38, 38))
        self.menuExport.setMaximumSize(QtCore.QSize(38, 38))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuExport.setIcon(icon4)
        self.menuExport.setIconSize(QtCore.QSize(24, 24))
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.horizontalLayout_6.addWidget(self.menuExport)
        self.line_3 = QtGui.QFrame(self.mainToolBarFrame)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_6.addWidget(self.line_3)
        self.menuUndo = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuUndo.setMinimumSize(QtCore.QSize(38, 38))
        self.menuUndo.setMaximumSize(QtCore.QSize(38, 38))
        self.menuUndo.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuUndo.setIcon(icon5)
        self.menuUndo.setObjectName(_fromUtf8("menuUndo"))
        self.horizontalLayout_6.addWidget(self.menuUndo)
        self.menuRedo = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuRedo.setMinimumSize(QtCore.QSize(36, 36))
        self.menuRedo.setMaximumSize(QtCore.QSize(36, 36))
        self.menuRedo.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuRedo.setIcon(icon6)
        self.menuRedo.setObjectName(_fromUtf8("menuRedo"))
        self.horizontalLayout_6.addWidget(self.menuRedo)
        self.line = QtGui.QFrame(self.mainToolBarFrame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_6.addWidget(self.line)
        self.menuDecSelect = QtGui.QComboBox(self.mainToolBarFrame)
        self.menuDecSelect.setMinimumSize(QtCore.QSize(200, 38))
        self.menuDecSelect.setMaximumSize(QtCore.QSize(200, 38))
        self.menuDecSelect.setObjectName(_fromUtf8("menuDecSelect"))
        self.horizontalLayout_6.addWidget(self.menuDecSelect)
        self.menuDecStart = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuDecStart.setMinimumSize(QtCore.QSize(38, 38))
        self.menuDecStart.setMaximumSize(QtCore.QSize(38, 38))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Scan film.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuDecStart.setIcon(icon7)
        self.menuDecStart.setIconSize(QtCore.QSize(24, 24))
        self.menuDecStart.setObjectName(_fromUtf8("menuDecStart"))
        self.horizontalLayout_6.addWidget(self.menuDecStart)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.menuSettings = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuSettings.setMinimumSize(QtCore.QSize(38, 38))
        self.menuSettings.setMaximumSize(QtCore.QSize(38, 38))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuSettings.setIcon(icon8)
        self.menuSettings.setIconSize(QtCore.QSize(24, 24))
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.horizontalLayout_6.addWidget(self.menuSettings)
        self.menuQuit = QtGui.QPushButton(self.mainToolBarFrame)
        self.menuQuit.setMinimumSize(QtCore.QSize(38, 38))
        self.menuQuit.setMaximumSize(QtCore.QSize(38, 38))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/free-design-icons/icons/free-design-icons/Exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuQuit.setIcon(icon9)
        self.menuQuit.setIconSize(QtCore.QSize(24, 24))
        self.menuQuit.setObjectName(_fromUtf8("menuQuit"))
        self.horizontalLayout_6.addWidget(self.menuQuit)
        self.verticalLayout_4.addWidget(self.mainToolBarFrame)
        self.mainContentFrame = QtGui.QFrame(vilaydetect)
        self.mainContentFrame.setObjectName(_fromUtf8("mainContentFrame"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.mainContentFrame)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitter = QtGui.QSplitter(self.mainContentFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.mainLeftFrame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainLeftFrame.sizePolicy().hasHeightForWidth())
        self.mainLeftFrame.setSizePolicy(sizePolicy)
        self.mainLeftFrame.setObjectName(_fromUtf8("mainLeftFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mainLeftFrame)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter_2 = QtGui.QSplitter(self.mainLeftFrame)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(4)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.filmBox = QtGui.QFrame(self.splitter_2)
        self.filmBox.setObjectName(_fromUtf8("filmBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.filmBox)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.filmViewBox = QtGui.QFrame(self.filmBox)
        self.filmViewBox.setObjectName(_fromUtf8("filmViewBox"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.filmViewBox)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.filmView = FilmView(self.filmViewBox)
        self.filmView.setMinimumSize(QtCore.QSize(200, 150))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.filmView.setBackgroundBrush(brush)
        self.filmView.setObjectName(_fromUtf8("filmView"))
        self.horizontalLayout_10.addWidget(self.filmView)
        self.verticalLayout.addWidget(self.filmViewBox)
        self.filmControlFrame = QtGui.QFrame(self.filmBox)
        self.filmControlFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.filmControlFrame.setObjectName(_fromUtf8("filmControlFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.filmControlFrame)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.filmLayoutFrame = QtGui.QFrame(self.filmControlFrame)
        self.filmLayoutFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.filmLayoutFrame.setObjectName(_fromUtf8("filmLayoutFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.filmLayoutFrame)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(8)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.filmTimeLabel = QtGui.QLabel(self.filmLayoutFrame)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filmTimeLabel.setFont(font)
        self.filmTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filmTimeLabel.setObjectName(_fromUtf8("filmTimeLabel"))
        self.gridLayout_2.addWidget(self.filmTimeLabel, 1, 3, 1, 1)
        self.filmTimeButtonsFrame = QtGui.QFrame(self.filmLayoutFrame)
        self.filmTimeButtonsFrame.setObjectName(_fromUtf8("filmTimeButtonsFrame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.filmTimeButtonsFrame)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.filmPrevTimeButton = QtGui.QPushButton(self.filmTimeButtonsFrame)
        self.filmPrevTimeButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmPrevTimeButton.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filmPrevTimeButton.setIcon(icon10)
        self.filmPrevTimeButton.setObjectName(_fromUtf8("filmPrevTimeButton"))
        self.horizontalLayout_5.addWidget(self.filmPrevTimeButton)
        self.filmTimeSpinBox = QtGui.QDoubleSpinBox(self.filmTimeButtonsFrame)
        self.filmTimeSpinBox.setDecimals(2)
        self.filmTimeSpinBox.setMinimum(0.01)
        self.filmTimeSpinBox.setMaximum(9.99)
        self.filmTimeSpinBox.setSingleStep(0.1)
        self.filmTimeSpinBox.setProperty("value", 2.0)
        self.filmTimeSpinBox.setObjectName(_fromUtf8("filmTimeSpinBox"))
        self.horizontalLayout_5.addWidget(self.filmTimeSpinBox)
        self.filmNextTimeButton = QtGui.QPushButton(self.filmTimeButtonsFrame)
        self.filmNextTimeButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmNextTimeButton.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filmNextTimeButton.setIcon(icon11)
        self.filmNextTimeButton.setObjectName(_fromUtf8("filmNextTimeButton"))
        self.horizontalLayout_5.addWidget(self.filmNextTimeButton)
        self.gridLayout_2.addWidget(self.filmTimeButtonsFrame, 3, 3, 1, 1)
        self.filmFrameButtonsFrame = QtGui.QFrame(self.filmLayoutFrame)
        self.filmFrameButtonsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.filmFrameButtonsFrame.setObjectName(_fromUtf8("filmFrameButtonsFrame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.filmFrameButtonsFrame)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.filmPrevFrameButton = QtGui.QPushButton(self.filmFrameButtonsFrame)
        self.filmPrevFrameButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmPrevFrameButton.setText(_fromUtf8(""))
        self.filmPrevFrameButton.setIcon(icon10)
        self.filmPrevFrameButton.setObjectName(_fromUtf8("filmPrevFrameButton"))
        self.horizontalLayout_3.addWidget(self.filmPrevFrameButton)
        self.filmNextFrameButton = QtGui.QPushButton(self.filmFrameButtonsFrame)
        self.filmNextFrameButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmNextFrameButton.setText(_fromUtf8(""))
        self.filmNextFrameButton.setIcon(icon11)
        self.filmNextFrameButton.setObjectName(_fromUtf8("filmNextFrameButton"))
        self.horizontalLayout_3.addWidget(self.filmNextFrameButton)
        self.gridLayout_2.addWidget(self.filmFrameButtonsFrame, 3, 1, 1, 1)
        self.filmFrameLabel = QtGui.QLabel(self.filmLayoutFrame)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.filmFrameLabel.setFont(font)
        self.filmFrameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filmFrameLabel.setObjectName(_fromUtf8("filmFrameLabel"))
        self.gridLayout_2.addWidget(self.filmFrameLabel, 1, 1, 1, 1)
        self.filmShotLabel = QtGui.QLabel(self.filmLayoutFrame)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filmShotLabel.setFont(font)
        self.filmShotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filmShotLabel.setObjectName(_fromUtf8("filmShotLabel"))
        self.gridLayout_2.addWidget(self.filmShotLabel, 1, 2, 1, 1)
        self.filmShotButtonsFrame = QtGui.QFrame(self.filmLayoutFrame)
        self.filmShotButtonsFrame.setObjectName(_fromUtf8("filmShotButtonsFrame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.filmShotButtonsFrame)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.filmPrevElementButton = QtGui.QPushButton(self.filmShotButtonsFrame)
        self.filmPrevElementButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmPrevElementButton.setText(_fromUtf8(""))
        self.filmPrevElementButton.setIcon(icon10)
        self.filmPrevElementButton.setObjectName(_fromUtf8("filmPrevElementButton"))
        self.horizontalLayout_4.addWidget(self.filmPrevElementButton)
        self.filmNextElementButton = QtGui.QPushButton(self.filmShotButtonsFrame)
        self.filmNextElementButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmNextElementButton.setText(_fromUtf8(""))
        self.filmNextElementButton.setIcon(icon11)
        self.filmNextElementButton.setObjectName(_fromUtf8("filmNextElementButton"))
        self.horizontalLayout_4.addWidget(self.filmNextElementButton)
        self.gridLayout_2.addWidget(self.filmShotButtonsFrame, 3, 2, 1, 1)
        self.filmPlayPauseLabel = QtGui.QLabel(self.filmLayoutFrame)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filmPlayPauseLabel.setFont(font)
        self.filmPlayPauseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filmPlayPauseLabel.setObjectName(_fromUtf8("filmPlayPauseLabel"))
        self.gridLayout_2.addWidget(self.filmPlayPauseLabel, 1, 0, 1, 1)
        self.filmPlayPauseButtonsFrame = QtGui.QFrame(self.filmLayoutFrame)
        self.filmPlayPauseButtonsFrame.setObjectName(_fromUtf8("filmPlayPauseButtonsFrame"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.filmPlayPauseButtonsFrame)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.filmPlayButton = QtGui.QPushButton(self.filmPlayPauseButtonsFrame)
        self.filmPlayButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmPlayButton.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filmPlayButton.setIcon(icon12)
        self.filmPlayButton.setObjectName(_fromUtf8("filmPlayButton"))
        self.horizontalLayout_8.addWidget(self.filmPlayButton)
        self.filmPauseButton = QtGui.QPushButton(self.filmPlayPauseButtonsFrame)
        self.filmPauseButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmPauseButton.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filmPauseButton.setIcon(icon13)
        self.filmPauseButton.setObjectName(_fromUtf8("filmPauseButton"))
        self.horizontalLayout_8.addWidget(self.filmPauseButton)
        self.filmStopButton = QtGui.QPushButton(self.filmPlayPauseButtonsFrame)
        self.filmStopButton.setMaximumSize(QtCore.QSize(26, 26))
        self.filmStopButton.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filmStopButton.setIcon(icon14)
        self.filmStopButton.setObjectName(_fromUtf8("filmStopButton"))
        self.horizontalLayout_8.addWidget(self.filmStopButton)
        self.gridLayout_2.addWidget(self.filmPlayPauseButtonsFrame, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.filmLayoutFrame)
        self.frame = QtGui.QFrame(self.filmControlFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(14)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout.addWidget(self.frame)
        self.filmZoomTimeFrame = QtGui.QFrame(self.filmControlFrame)
        self.filmZoomTimeFrame.setObjectName(_fromUtf8("filmZoomTimeFrame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.filmZoomTimeFrame)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.filmZoomButtonsFrame = QtGui.QFrame(self.filmZoomTimeFrame)
        self.filmZoomButtonsFrame.setObjectName(_fromUtf8("filmZoomButtonsFrame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.filmZoomButtonsFrame)
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem1 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.filmZoom1x = QtGui.QPushButton(self.filmZoomButtonsFrame)
        self.filmZoom1x.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filmZoom1x.setFont(font)
        self.filmZoom1x.setObjectName(_fromUtf8("filmZoom1x"))
        self.horizontalLayout_9.addWidget(self.filmZoom1x)
        self.filmZoom2x = QtGui.QPushButton(self.filmZoomButtonsFrame)
        self.filmZoom2x.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filmZoom2x.setFont(font)
        self.filmZoom2x.setObjectName(_fromUtf8("filmZoom2x"))
        self.horizontalLayout_9.addWidget(self.filmZoom2x)
        self.filmZoom4x = QtGui.QPushButton(self.filmZoomButtonsFrame)
        self.filmZoom4x.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filmZoom4x.setFont(font)
        self.filmZoom4x.setObjectName(_fromUtf8("filmZoom4x"))
        self.horizontalLayout_9.addWidget(self.filmZoom4x)
        self.verticalLayout_6.addWidget(self.filmZoomButtonsFrame)
        self.filmTimeFrame = QtGui.QLabel(self.filmZoomTimeFrame)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filmTimeFrame.setFont(font)
        self.filmTimeFrame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filmTimeFrame.setObjectName(_fromUtf8("filmTimeFrame"))
        self.verticalLayout_6.addWidget(self.filmTimeFrame)
        self.horizontalLayout.addWidget(self.filmZoomTimeFrame)
        self.verticalLayout.addWidget(self.filmControlFrame)
        self.navigationBar = NavigationBar(self.filmBox)
        self.navigationBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.navigationBar.setFrameShape(QtGui.QFrame.NoFrame)
        self.navigationBar.setFrameShadow(QtGui.QFrame.Plain)
        self.navigationBar.setLineWidth(0)
        self.navigationBar.setObjectName(_fromUtf8("navigationBar"))
        self.verticalLayout.addWidget(self.navigationBar)
        self.annotationTimeViewFrame = QtGui.QFrame(self.splitter_2)
        self.annotationTimeViewFrame.setObjectName(_fromUtf8("annotationTimeViewFrame"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.annotationTimeViewFrame)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.annotationTimeView = QtGui.QGraphicsView(self.annotationTimeViewFrame)
        self.annotationTimeView.setObjectName(_fromUtf8("annotationTimeView"))
        self.verticalLayout_7.addWidget(self.annotationTimeView)
        self.navigationToolBar = QtGui.QFrame(self.annotationTimeViewFrame)
        self.navigationToolBar.setObjectName(_fromUtf8("navigationToolBar"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.navigationToolBar)
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.annotationTimeViewCustomize = QtGui.QPushButton(self.navigationToolBar)
        self.annotationTimeViewCustomize.setMinimumSize(QtCore.QSize(22, 22))
        self.annotationTimeViewCustomize.setMaximumSize(QtCore.QSize(22, 22))
        self.annotationTimeViewCustomize.setText(_fromUtf8(""))
        self.annotationTimeViewCustomize.setIcon(icon8)
        self.annotationTimeViewCustomize.setIconSize(QtCore.QSize(14, 14))
        self.annotationTimeViewCustomize.setObjectName(_fromUtf8("annotationTimeViewCustomize"))
        self.horizontalLayout_13.addWidget(self.annotationTimeViewCustomize)
        self.verticalLayout_7.addWidget(self.navigationToolBar)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.annotationTextViewFrame = QtGui.QFrame(self.splitter)
        self.annotationTextViewFrame.setMinimumSize(QtCore.QSize(30, 0))
        self.annotationTextViewFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.annotationTextViewFrame.setObjectName(_fromUtf8("annotationTextViewFrame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.annotationTextViewFrame)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.annotationTextView = QtGui.QTableView(self.annotationTextViewFrame)
        self.annotationTextView.setObjectName(_fromUtf8("annotationTextView"))
        self.verticalLayout_5.addWidget(self.annotationTextView)
        self.frame_6 = QtGui.QFrame(self.annotationTextViewFrame)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.annotationTextViewCustomize = QtGui.QPushButton(self.frame_6)
        self.annotationTextViewCustomize.setMinimumSize(QtCore.QSize(22, 22))
        self.annotationTextViewCustomize.setMaximumSize(QtCore.QSize(22, 22))
        self.annotationTextViewCustomize.setText(_fromUtf8(""))
        self.annotationTextViewCustomize.setIcon(icon8)
        self.annotationTextViewCustomize.setIconSize(QtCore.QSize(14, 14))
        self.annotationTextViewCustomize.setObjectName(_fromUtf8("annotationTextViewCustomize"))
        self.horizontalLayout_12.addWidget(self.annotationTextViewCustomize)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.annotationTreeFrame = QtGui.QFrame(self.splitter)
        self.annotationTreeFrame.setMinimumSize(QtCore.QSize(30, 0))
        self.annotationTreeFrame.setObjectName(_fromUtf8("annotationTreeFrame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.annotationTreeFrame)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.annotationTree = AnnotationTree(self.annotationTreeFrame)
        self.annotationTree.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.annotationTree.setDragEnabled(True)
        self.annotationTree.setDragDropOverwriteMode(True)
        self.annotationTree.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.annotationTree.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.annotationTree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.annotationTree.setHeaderHidden(True)
        self.annotationTree.setObjectName(_fromUtf8("annotationTree"))
        self.annotationTree.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_2.addWidget(self.annotationTree)
        self.frame_5 = QtGui.QFrame(self.annotationTreeFrame)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_11.setSpacing(3)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.annotationTreeShowFrameCheckbox = QtGui.QCheckBox(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.annotationTreeShowFrameCheckbox.setFont(font)
        self.annotationTreeShowFrameCheckbox.setObjectName(_fromUtf8("annotationTreeShowFrameCheckbox"))
        self.horizontalLayout_11.addWidget(self.annotationTreeShowFrameCheckbox)
        self.annotationTreeCustomize = QtGui.QPushButton(self.frame_5)
        self.annotationTreeCustomize.setMinimumSize(QtCore.QSize(22, 22))
        self.annotationTreeCustomize.setMaximumSize(QtCore.QSize(22, 22))
        self.annotationTreeCustomize.setText(_fromUtf8(""))
        self.annotationTreeCustomize.setIcon(icon8)
        self.annotationTreeCustomize.setIconSize(QtCore.QSize(14, 14))
        self.annotationTreeCustomize.setObjectName(_fromUtf8("annotationTreeCustomize"))
        self.horizontalLayout_11.addWidget(self.annotationTreeCustomize)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout_4.addWidget(self.mainContentFrame)

        self.retranslateUi(vilaydetect)
        QtCore.QMetaObject.connectSlotsByName(vilaydetect)

    def retranslateUi(self, vilaydetect):
        vilaydetect.setWindowTitle(QtGui.QApplication.translate("vilaydetect", "vilay detect", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setToolTip(QtGui.QApplication.translate("vilaydetect", "Create new file", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setToolTip(QtGui.QApplication.translate("vilaydetect", "Open file", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setToolTip(QtGui.QApplication.translate("vilaydetect", "Save file", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImport.setToolTip(QtGui.QApplication.translate("vilaydetect", "Import file", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setToolTip(QtGui.QApplication.translate("vilaydetect", "Export file", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUndo.setToolTip(QtGui.QApplication.translate("vilaydetect", "Undo last action", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRedo.setToolTip(QtGui.QApplication.translate("vilaydetect", "Redo action", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDecSelect.setToolTip(QtGui.QApplication.translate("vilaydetect", "Choose detector", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDecStart.setToolTip(QtGui.QApplication.translate("vilaydetect", "Start detector", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setToolTip(QtGui.QApplication.translate("vilaydetect", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQuit.setToolTip(QtGui.QApplication.translate("vilaydetect", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.filmTimeLabel.setText(QtGui.QApplication.translate("vilaydetect", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.filmTimeSpinBox.setSuffix(QtGui.QApplication.translate("vilaydetect", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.filmFrameLabel.setText(QtGui.QApplication.translate("vilaydetect", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.filmShotLabel.setText(QtGui.QApplication.translate("vilaydetect", "Element", None, QtGui.QApplication.UnicodeUTF8))
        self.filmPlayPauseLabel.setText(QtGui.QApplication.translate("vilaydetect", "Play/Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.filmZoom1x.setText(QtGui.QApplication.translate("vilaydetect", "1x", None, QtGui.QApplication.UnicodeUTF8))
        self.filmZoom2x.setText(QtGui.QApplication.translate("vilaydetect", "2x", None, QtGui.QApplication.UnicodeUTF8))
        self.filmZoom4x.setText(QtGui.QApplication.translate("vilaydetect", "4x", None, QtGui.QApplication.UnicodeUTF8))
        self.filmTimeFrame.setText(QtGui.QApplication.translate("vilaydetect", "Frame 0/0<br>\n"
"Time 0:00.000 / 0:00.000", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationTreeShowFrameCheckbox.setText(QtGui.QApplication.translate("vilaydetect", "show frame", None, QtGui.QApplication.UnicodeUTF8))

from AnnotationTree import AnnotationTree
from NavigationBar import NavigationBar
from FilmView import FilmView
import ressource_rc
